# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: nikody/mytaptrack-bitbucketpipeline-serverless

pipelines:
  default:
  branches:
    master:
      - step:
          name: Publish
          deployment: Production
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - npm install
            - npm run lint
            - npm run build
            - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - npm run release
