version: 0.2
  
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g jest
      - npm install -g typescript
    finally:
      - echo Install Complete
  pre_build:
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm install
  build:
    commands:
      - npm run build
      - npm version patch
      - npm push
      - npm run release
  post_build:
    commands:
      - echo Build completed on `date`
    finally:
      - rm -f ~/.npmrc
 